name: admin-pre
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo ---- Install GIT ---
          sudo apt-get install git
          echo ---- Remove the last repo ---
          sudo rm -rf /var/www/admin.funkysheep.net
          echo ---- Cloning the repository ---
          sudo git clone https://github.com/FunkySheepStudio/Server.git /var/www/admin.funkysheep.net